name: elephant_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_progress_button: ^1.0.0
  cached_network_image: ^2.2.0+1
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  http: ^0.12.2
  get_it: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0

flutter:  
  uses-material-design: true   
  assets:
   - assets/images/elephant_icon.png   
   - assets/images/background_home.jpg
   - assets/images/background_list.jpg
   - assets/images/background_sort.jpg   

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
        - asset: assets/fonts/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora-Italic.ttf
        - asset: assets/fonts/Lora-Medium.ttf
        - asset: assets/fonts/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora-SemiBoldItalic.ttf
          weight: 700
  

  
